const constants = {

    PROTEIN_ID: '1ddca711-0dcc-4708-93c2-1ac3b0b3d281',
    FAT_ID: '9fa87e51-46af-4ca9-8c7d-98176cfa8b78',
    CARB_ID: 'fa5f03f8-6aeb-4d5f-9100-f41cd606d36b',

    // Actions
    FETCH_NUTRIENTS: "FETCH_NUTRIENTS",
    FETCH_NUTRIENT_TARGETS: "FETCH_NUTRIENT_TARGETS",
    FETCH_MEALS: "FETCH_MEALS",

    SAVE_NUTRIENT_SETTINGS: "SAVE_NUTRIENT_SETTINGS",
    SAVE_NUTRIENT_TARGETS: "SAVE_NUTRIENT_TARGETS",
    SAVE_MEAL: "SAVE_MEAL",
    DELETE_MEAL: "DELETE_MEAL",

    FETCH_PROFILE: "FETCH_PROFILE",

    FETCH_MUSCLEGROUPS: "FETCH_MUSCLEGROUPS",
    FETCH_EXERCISES: "FETCH_EXERCISES",
    FETCH_ROUTINES: "FETCH_ROUTINES",
    FETCH_ACTIVE_ROUTINE: "FETCH_ACTIVE_ROUTINE",
    FETCH_WORKOUTS: "FETCH_WORKOUTS",

    SAVE_EXERCISE: 'SAVE_EXERCISE',
    DELETE_EXERCISE: 'DELETE_EXERCISE',
    SAVE_ROUTINE: 'SAVE_ROUTINE',
    DELETE_ROUTINE:'DELETE_ROUTINE',

    // Mutations
    FETCH_NUTRIENTS_SUCCESS: "FETCH_NUTRIENTS_SUCCESS",
    FETCH_NUTRIENT_TARGETS_SUCCESS: "FETCH_NUTRIENT_TARGETS_SUCCESS",
    FETCH_MEALS_SUCCESS: "FETCH_MEALS_SUCCESS",
    SAVE_NUTRIENT_SETTINGS_SUCCESS: "SAVE_NUTRIENT_SETTINGS_SUCCESS",   
    SAVE_NUTRIENT_TARGETS_SUCCESS: "SAVE_NUTRIENT_TARGETS_SUCCESS",
    SAVE_MEAL_SUCCESS: "SAVE_MEAL_SUCCESS",
    DELETE_MEAL_SUCCESS: "DELETE_MEAL_SUCCESS",


    
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",


    FETCH_MUSCLEGROUPS_SUCCESS: "FETCH_MUSCLEGROUPS_SUCCESS",
    FETCH_EXERCISES_SUCCESS: "FETCH_EXERCISES_SUCCESS",
    FETCH_ROUTINES_SUCCESS: "FETCH_ROUTINES_SUCCESS", 
    FETCH_ACTIVE_ROUTINE_SUCCESS: "FETCH_ACTIVE_ROUTINE_SUCCESS",
    FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",

    SAVE_EXERCISE_SUCCESS: 'SAVE_EXERCISE_SUCCESS',
    DELETE_EXERCISE_SUCCESS: 'DELETE_EXERCISE_SUCCESS',
    SAVE_ROUTINE_SUCCESS: 'SAVE_ROUTINE_SUCCESS',
    DELETE_ROUTINE_SUCCESS: 'DELETE_ROUTINE_SUCCESS',
}

module.exports = constants