const constants = {

    FETCH_NUTRIENTS: "FETCH_NUTRIENTS",
    FETCH_NUTRIENTS_STARTED: "FETCH_NUTRIENTS_STARTED",
    FETCH_NUTRIENTS_SUCCESS: "FETCH_NUTRIENTS_SUCCESS",
    FETCH_NUTRIENTS_FAILURE: "FETCH_NUTRIENTS_FAILURE",
    PROTEIN_ID: '1ddca711-0dcc-4708-93c2-1ac3b0b3d281',
    FAT_ID: '9fa87e51-46af-4ca9-8c7d-98176cfa8b78',
    CARB_ID: 'fa5f03f8-6aeb-4d5f-9100-f41cd606d36b',
    FETCH_NUTRIENT_TARGETS: "FETCH_NUTRIENT_TARGETS",

    FETCH_MEALS: "FETCH_MEALS",
    FETCH_MEALS_STARTED: "FETCH_MEALS_STARTED",
    FETCH_MEALS_SUCCESS: "FETCH_MEALS_SUCCESS",
    FETCH_MEALS_FAILURE: "FETCH_MEALS_FAILURE",

    SAVE_MEAL: "SAVE_MEAL",
    SAVE_MEAL_STARTED: "SAVE_MEAL_STARTED",
    SAVE_MEAL_SUCCESS: "SAVE_MEAL_SUCCESS",
    SAVE_MEAL_FAILURE: "SAVE_MEAL_FAILURE",

    DELETE_MEAL: "DELETE_MEAL",
    DELETE_MEAL_STARTED: "DELETE_MEAL_STARTED",
    DELETE_MEAL_SUCCESS: "DELETE_MEAL_SUCCESS",
    DELETE_MEAL_FAILURE: "DELETE_MEAL_FAILURE",

    FETCH_PROFILE: "FETCH_PROFILE",
    FETCH_PROFILE_STARTED: "FETCH_PROFILE_STARTED",
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",


    FETCH_ROUTINES: "FETCH_ROUTINES",
    FETCH_ROUTINES_STARTED: "FETCH_ROUTINES_STARTED",
    FETCH_ROUTINES_SUCCESS: "FETCH_ROUTINES_SUCCESS",
    FETCH_ROUTINES_FAILURE: "FETCH_ROUTINES_FAILURE",

    FETCH_ACTIVE_ROUTINE: "FETCH_ACTIVE_ROUTINE",
    FETCH_ACTIVE_ROUTINE_STARTED: "FETCH_ACTIVE_ROUTINE_STARTED",
    FETCH_ACTIVE_ROUTINE_SUCCESS: "FETCH_ACTIVE_ROUTINE_SUCCESS",
    FETCH_ACTIVE_ROUTINE_FAILURE: "FETCH_ACTIVE_ROUTINE_FAILURE",

    FETCH_WORKOUTS: "FETCH_WORKOUTS",
    FETCH_WORKOUTS_STARTED: "FETCH_WORKOUTS_STARTED",
    FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
    FETCH_WORKOUTS_FAILURE: "FETCH_WORKOUTS_FAILURE",
}

module.exports = constants